constants = {
    "EVENT_NOT_STARTED": "Event not started yet. Try again after the event starts",
    "NO_TEAM_JOINED": "No team available. Join a team first",
    "INTERNAL_ERROR": "Internal Error",
    "FEAT_ALREADY_GENERATED": "Features already generated",
    "INVALID_STATE": "Invalid state encountered",
    "INVALID_AUTH_STATE": "Invalid authentication scheme",
    "INVALID_AUTH_CODE": "Invalid authorization code",
    "INVALID_AUTH_SCHEME": "Invalid authentication scheme",
    "USER_NOT_CREATED": "User not created yet",
    "USER_HAS_TEAM": "User has already joined a team",
    "TEAM_NAME_EXISTS": "Requested team name already exists",
    "TEAM_FULL": "Requested team is full",
    "EVENT_STARTED": "Event has stated. Cannot perform the requested changes now",
    "INVALID_CODE": "The entered team code is invalid",
    "OWN_TEAM": "Cannot join your own team",
}
